# Generated by Django 4.1 on 2022-08-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('SurName', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=300)),
                ('Password', models.TextField(max_length=300)),
            ],
        ),
    ]
